name: ${name}
description: Very epic, yet simplistic, forcefield plugin!
authors:
  - srnyx
website: https://srnyx.xyz

main: xyz.srnyx.forcefield.ForceField
version: ${version}

commands:
  forcefield:
    description: Main command for the ForceField plugin
    aliases:
      - ff
    permission: forcefield.command

permissions:
  forcefield.command:
    description: Allows access to the base command
  forcefield.command.toggle:
    description: Allows access to toggle the forcefield
  forcefield.command.mobs:
    description: Allows access to toggle the forcefield for mobs
  forcefield.command.radius:
    description: Allows access to change the radius of the forcefield
  forcefield.command.strength:
    description: Allows access to change the strength of the forcefield
  forcefield.command.reload:
    description: Allows access to reload the plugin (config and player data)
  forcefield.others:
    description: Allows using the commands on other players
  forcefield.bypass:
    description: Allows bypassing other players' forcefields
